version: '2'

services:

### Code container
  workspace:
    build:
      context: ./workspace
    depends_on:
      - mysql
    command: ["waitforit","-host=mysql","-port=3306","-timeout=30","-debug"]

### Apache Server Container #################################
  apache2:
    build:
      context: ./apache2
      args:
        - PHP_UPSTREAM_CONTAINER=php-fpm
        - PHP_UPSTREAM_PORT=9000
        - SERVER_ALIAS=${SERVER_ALIAS}
        - SERVER_PORT=${SERVER_PORT}
    volumes:
      - ./logs/apache2:/var/log/apache2
    ports:
      - "${SERVER_PORT}:80"
      - "${SERVER_SSL_PORT}:443"
    links:
      - php-fpm

### PHP-FPM Container #######################################
#php-fpm 7.1

  php-fpm:
    build:
      context: ./php-fpm
    expose:
      - "9000"
    links:
      - workspace

### Redis Container #########################################

  redis:
    build:
      context: ./redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

# mysql 5.7.17
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

volumes:
    mysql:
      driver: "local"
    redis:
      driver: "local"